data:
  binary_file: ./Data/AsteroidModel01_shape_public/Asteroid1_lightcurve_data/Asteroid01_lightcurve_binary.txt
  binary_file_blender: ./Data/AsteroidModel01_shape_public/Asteroid1_lightcurve_data/Asteroid01_lightcurve_binary_blender.txt
  intensity_file: ./Data/AsteroidModel01_shape_public/Asteroid1_lightcurve_data/Asteroid01_lightcurve_intensity.txt
  intensity_file_blender: ./Data/AsteroidModel01_shape_public/Asteroid1_lightcurve_data/Asteroid01_lightcurve_intensity_blender.txt
model:
  LMAX: 9
  dtype: torch.float64
  hypernet: warmstart_points
  nrows: 12
  warm_start_checkpoint: ./runs/[RUN_NAME]/checkpoint.pt
  warm_start_generator: points
  warm_start_generator_kwargs: {}
optimizer: ADAM
output:
  base_dir: ./runs
physical:
  blender_loss_weight: 0.12302694333443927
  cylinder_radius: 1.12
  fit_omega: false
  period: 882.0
run_name: BEST_refine_obj1
tol: 81
training:
  lambda_binary_end: 0.5875335449769012
  lambda_binary_start: 0.5875335449769012
  lambda_intensity_end: 22.08453213662722
  lambda_intensity_start: 22.08453213662722
  log_every: 20
  lr: 1.4138878516685303e-06
  seed: 0
  steps: 5000
validation:
  enabled: true
  every: log_every
  gt_path: ./Data/AsteroidModel01_shape_public/asteroid1.stl
  voxel_size: 0.02
